const tasks = [
  {
    id: 1,
    title: "Task 1",
    description: "Description for Task 1",
    status: "pending",
    pomodoroCount: 4,
    completedPomodoros: 2,
    dueDate: "2023-12-31",
    priority: "high",
  },
  {
    id: 2,
    title: "Task 2",
    description: "Description for Task 2",
    status: "completed",
    pomodoroCount: 2,
    completedPomodoros: 2,
    dueDate: "2023-11-30",
    priority: "medium",
  },
  {
    id: 3,
    title: "Task 3",
    description: "Description for Task 3",
    status: "in-progress",
    pomodoroCount: 5,
    completedPomodoros: 3,
    dueDate: "2024-01-15",
    priority: "low",
  },
  {
    id: 4,
    title: "Task 4",
    description: "Description for Task 4",
    status: "pending",
    pomodoroCount: 3,
    completedPomodoros: 1,
    dueDate: "2024-02-10",
    priority: "high",
  },
  {
    id: 5,
    title: "Task 5",
    description: "Description for Task 5",
    status: "completed",
    pomodoroCount: 6,
    completedPomodoros: 6,
    dueDate: "2023-10-15",
    priority: "medium",
  },
  {
    id: 6,
    title: "Task 6",
    description: "Description for Task 6",
    status: "in-progress",
    pomodoroCount: 8,
    completedPomodoros: 5,
    dueDate: "2024-03-01",
    priority: "low",
  },
  {
    id: 7,
    title: "Task 7",
    description: "Description for Task 7",
    status: "pending",
    pomodoroCount: 2,
    completedPomodoros: 0,
    dueDate: "2023-12-10",
    priority: "high",
  },
  {
    id: 8,
    title: "Task 8",
    description: "Description for Task 8",
    status: "completed",
    pomodoroCount: 4,
    completedPomodoros: 4,
    dueDate: "2023-09-20",
    priority: "low",
  },
  {
    id: 9,
    title: "Task 9",
    description: "Description for Task 9",
    status: "in-progress",
    pomodoroCount: 10,
    completedPomodoros: 6,
    dueDate: "2024-01-01",
    priority: "medium",
  },
  {
    id: 10,
    title: "Task 10",
    description: "Description for Task 10",
    status: "pending",
    pomodoroCount: 7,
    completedPomodoros: 2,
    dueDate: "2024-05-05",
    priority: "high",
  },
  {
    id: 11,
    title: "Task 11",
    description: "Description for Task 11",
    status: "completed",
    pomodoroCount: 3,
    completedPomodoros: 3,
    dueDate: "2023-08-25",
    priority: "medium",
  },
  {
    id: 12,
    title: "Task 12",
    description: "Description for Task 12",
    status: "pending",
    pomodoroCount: 6,
    completedPomodoros: 0,
    dueDate: "2024-04-20",
    priority: "low",
  },
  {
    id: 13,
    title: "Task 13",
    description: "Description for Task 13",
    status: "in-progress",
    pomodoroCount: 5,
    completedPomodoros: 2,
    dueDate: "2023-12-05",
    priority: "high",
  },
  {
    id: 14,
    title: "Task 14",
    description: "Description for Task 14",
    status: "completed",
    pomodoroCount: 9,
    completedPomodoros: 9,
    dueDate: "2023-11-01",
    priority: "medium",
  },
  {
    id: 15,
    title: "Task 15",
    description: "Description for Task 15",
    status: "pending",
    pomodoroCount: 4,
    completedPomodoros: 1,
    dueDate: "2024-02-28",
    priority: "low",
  },
];

export default tasks;
