import { Task } from "../types";

const tasks: Task[] = [
  {
    id: "1",
    title: "Complete Project Proposal",
    description: "Draft and finalize the project proposal for the new client.",
    status: "pending",
    pomodoroCount: 4,
    completedPomodoros: 2,
    dueDate: new Date("2023-12-31"),
    priority: "high",
    category: "work",
  },
  {
    id: "2",
    title: "Grocery Shopping",
    description:
      "Buy groceries for the week, including fruits, vegetables, and dairy products.",
    status: "completed",
    pomodoroCount: 2,
    completedPomodoros: 2,
    dueDate: new Date("2023-11-30"),
    priority: "medium",
    category: "personal",
  },
  {
    id: "3",
    title: "Read 'Clean Code'",
    description: "Read chapters 1-3 of 'Clean Code' by Robert C. Martin.",
    status: "inProgress",
    pomodoroCount: 5,
    completedPomodoros: 3,
    dueDate: new Date("2024-01-15"),
    priority: "low",
    category: "study",
  },
  {
    id: "4",
    title: "Prepare Presentation",
    description:
      "Create slides and practice the presentation for the upcoming meeting.",
    status: "pending",
    pomodoroCount: 3,
    completedPomodoros: 1,
    dueDate: new Date("2024-02-10"),
    priority: "high",
    category: "work",
  },
  {
    id: "5",
    title: "Exercise",
    description: "Complete a 30-minute workout session.",
    status: "completed",
    pomodoroCount: 6,
    completedPomodoros: 6,
    dueDate: new Date("2023-10-15"),
    priority: "medium",
    category: "personal",
  },
  {
    id: "6",
    title: "Update Resume",
    description:
      "Revise and update the resume with recent job experiences and skills.",
    status: "inProgress",
    pomodoroCount: 8,
    completedPomodoros: 5,
    dueDate: new Date("2024-03-01"),
    priority: "low",
    category: "work",
  },
  {
    id: "7",
    title: "Plan Vacation",
    description: "Research and plan the itinerary for the upcoming vacation.",
    status: "pending",
    pomodoroCount: 2,
    completedPomodoros: 0,
    dueDate: new Date("2023-12-10"),
    priority: "high",
    category: "personal",
  },
  {
    id: "8",
    title: "Organize Workspace",
    description: "Clean and organize the workspace for better productivity.",
    status: "completed",
    pomodoroCount: 4,
    completedPomodoros: 4,
    dueDate: new Date("2023-09-20"),
    priority: "low",
    category: "personal",
  },
  {
    id: "9",
    title: "Finish Assignment",
    description: "Complete the assignment for the online course.",
    status: "inProgress",
    pomodoroCount: 10,
    completedPomodoros: 6,
    dueDate: new Date("2024-01-01"),
    priority: "medium",
    category: "study",
  },
  {
    id: "10",
    title: "Client Meeting Preparation",
    description: "Prepare documents and agenda for the client meeting.",
    status: "pending",
    pomodoroCount: 7,
    completedPomodoros: 2,
    dueDate: new Date("2024-05-05"),
    priority: "high",
    category: "work",
  },
  {
    id: "11",
    title: "Cook Dinner",
    description: "Prepare a healthy dinner for the family.",
    status: "completed",
    pomodoroCount: 3,
    completedPomodoros: 3,
    dueDate: new Date("2023-08-25"),
    priority: "medium",
    category: "personal",
  },
  {
    id: "12",
    title: "Study for Exam",
    description: "Review notes and study for the upcoming exam.",
    status: "pending",
    pomodoroCount: 6,
    completedPomodoros: 0,
    dueDate: new Date("2024-04-20"),
    priority: "low",
    category: "study",
  },
  {
    id: "13",
    title: "Develop New Feature",
    description: "Work on developing a new feature for the project.",
    status: "inProgress",
    pomodoroCount: 5,
    completedPomodoros: 2,
    dueDate: new Date("2023-12-05"),
    priority: "high",
    category: "work",
  },
  {
    id: "14",
    title: "Write Blog Post",
    description: "Draft and publish a new blog post on the website.",
    status: "completed",
    pomodoroCount: 9,
    completedPomodoros: 9,
    dueDate: new Date("2023-11-01"),
    priority: "medium",
    category: "work",
  },
  {
    id: "15",
    title: "Gardening",
    description:
      "Spend time in the garden planting new flowers and vegetables.",
    status: "pending",
    pomodoroCount: 4,
    completedPomodoros: 1,
    dueDate: new Date("2024-02-28"),
    priority: "low",
    category: "personal",
  },
];

export default tasks;
